### ISSUE TITLE
Add ansible_host to the inventory

### ISSUE THREAD

**Issue by stijnchip** [bitmand/ansible-inventory#4]
This is exactly what I'm looking for. I'm just missing one thingis, is it possible to add ansible_host: to the inventory?

**Comment by bitmand** [comment]
@stijnchip sorry, I completely forgot to get back to you on this! It is possible to set `ansible_host` in the dynamic inventory, but I'm not sure I understand the problem it solves, because:

* If the host files is named `server1.yml` then Ansible will already try and SSH to `server1` (the name of the host in the inventory), so no need to set `ansible_host` explicitly.
* If you want to set `ansible_host` to something else than eg. `server1`, then you can just add it directly in the `server1.yml` file, which Ansible will read and use - so no need to set it in the dynamic inventory.

...but I might not understand your exact use-case? :)
